#include "neon/presets.h"
#include <string>
#include <vector>

namespace neon::core {
const std::vector<WritingPreset>& writingPresets() {
    static const std::vector<WritingPreset> presets = {
        {"book",
         "Book",
         "Manuscript",
         "Chapter",
         "Chapters",
         "Develop a long-form narrative, chapter by chapter.",
         "Literata",
         1,
         4,
         24,
         true,
         true,
         {{"chapter", "Opening", "Establish the voice, setting, and a reason to keep reading."}}},
        {"research",
         "Research Paper",
         "Paper",
         "Section",
         "Sections",
         "An empirical paper with an abstract, methods, findings, and references. Adapt the "
         "outline to your discipline.",
         "Literata",
         2,
         8,
         0,
         false,
         false,
         {{"abstract", "Abstract",
           "Summarize the question, approach, principal findings, and significance."},
          {"introduction", "Introduction",
           "Establish the problem, prior work, and research question."},
          {"methods", "Methods",
           "Describe the study design and enough detail to reproduce the work."},
          {"results", "Results",
           "Present the findings; distinguish observations from interpretation."},
          {"discussion", "Discussion", "Interpret the results, limitations, and implications."},
          {"references", "References",
           "List cited sources consistently. Citation management and LaTeX are not yet "
           "available."}}},
        {"newsletter",
         "Newsletter",
         "Issue",
         "Section",
         "Sections",
         "Shape an issue from the subject line to a clear closing call to action.",
         "Source Sans 3",
         1,
         12,
         0,
         false,
         false,
         {{"subject", "Subject & Preview",
           "Write a concise subject line and complementary preview text."},
          {"lead", "Lead Story", "Open with the one story readers should remember."},
          {"updates", "Updates", "Use short, scannable updates with descriptive headings."},
          {"links", "Worth Reading", "Collect useful resources with context and URLs."},
          {"closing", "Closing Note", "Close with one clear next step and a personal sign-off."}}},
        {"essay",
         "Essay",
         "Essay",
         "Section",
         "Sections",
         "Build a focused argument with evidence and a considered conclusion.",
         "Literata",
         1.5,
         8,
         0,
         false,
         false,
         {{"introduction", "Introduction", "Introduce the question and state your central claim."},
          {"argument", "Argument", "Develop the claim with evidence and address counterarguments."},
          {"conclusion", "Conclusion", "Bring the argument together and explain why it matters."},
          {"references", "Sources", "Record sources and attribution as you write."}}},
        {"meeting",
         "Meeting Notes",
         "Notes",
         "Topic",
         "Topics",
         "Prepare an agenda, capture decisions, and leave with clear actions.",
         "Source Sans 3",
         1,
         12,
         0,
         false,
         false,
         {{"agenda", "Agenda", "Record the purpose, attendees, and topics to cover."},
          {"discussion", "Discussion", "Capture key points and open questions by topic."},
          {"decisions", "Decisions", "Record each decision and its rationale."},
          {"actions", "Action Items", "Record the action, owner, and due date."}}}};
    return presets;
}
const WritingPreset* writingPreset(const std::string& id) {
    for (const auto& preset : writingPresets())
        if (preset.id == id)
            return &preset;
    return nullptr;
}
} // namespace neon::core
